#When set to true, a tree will only be chopped down if the player is sneaking.
reverse_sneaking = false
#When set to true, the mod will cut down trees in creative too.
break_in_creative = false

#Falling Tree configuration
[trees]
	#List of blocks that should not be considered as leaves.
	#INFO: This wins over the whitelist.
	logs_blacklisted = []
	#When set to true nether tree warts (leaves) will be broken along with the trunk.
	break_nether_tree_warts = true
	#When set to true, leaves that should naturally break will be broken instantly.
	leaves_breaking = true
	#The minimum amount of leaves that needs to be around the top most log in order for the mod to consider it a tree.
	#INFO: Only in INSTANTANEOUS mode.
	#Range: 0 ~ 5
	minimum_leaves_around_required = 1
	#Additional list of blocks considered as leaves.
	#INFO: Blocks marked with the leaves tag will already be whitelisted.
	logs_whitelisted = []
	#The maximum size of a tree. If there's more logs than this value the tree won't be cut.
	#INFO: Only in INSTANTANEOUS mode.
	#Range: > 1
	logs_max_count = 100
	#Radius to force break leaves. If another tree is still holding the leaves they'll still be broken. If the leaves are persistent (placed by player) they'll also be destroyed.
	#The radius is applied from one of the top most log blocks.
	#INFO: break_leaves must be activated for this to take effect.
	#INFO: Only in INSTANTANEOUS mode.
	#Range: 0 ~ 10
	leaves_breaking_force_radius = 0
	#How to break the tree.
	#Instantaneous will break it in one go.
	#Shift down will make the tree fall down as you cut it, so you still have to break x blocks but don't have to climb the tree for them.
	#Allowed Values: INSTANTANEOUS, SHIFT_DOWN
	break_mode = "INSTANTANEOUS"
	#When set to true this allow to have any kind of log in a tree trunk.
	#Otherwise (false) the trunk will be considered as being only one kind of log.
	allow_mixed_logs = false

[tools]
	#List of tools that should not be considered as tools.
	#INFO: This wins over the whitelist.
	blacklisted = []
	#When set to true, the mod will be activated no matter what you have in your hand (or empty hand).
	#INFO: Blacklist still can be use to restrict some tools.
	ignore_tools = false
	#Applies a speed modifier when breaking the tree.
	#0 will disable this, so the speed will be the default one of breaking a block.
	#If set to 1 each log block will be counted once, so if the tree is 5 blocks tall it'll require the time of breaking 5 logs.
	#If set to 2 each log block will be counted twice, so if the tree is 5 blocks tall, it'll require the time of breaking 10 logs
	#INFO: Only in INSTANTANEOUS mode.
	#WARNING: If you are on a server, this either has to be set to 0 or every player should have the mod. Else they'll have a weird effect of breaking the block but the block is still there.
	#Range: 0.0 ~ 50.0
	speed_multiplicand = 0.0
	#Additional list of tools that can be used to chop down a tree.
	#INFO: Items marked with the axe tag will already be whitelisted.
	whitelisted = []
	#Defines the number of times the damage is applied to the tool.
	#ie: if set to 1 then breaking 5 logs will give 5 damage.
	#ie: if set to 2 then breaking 5 logs will give 10 damage.
	#If set to 0, it'll still apply 1 damage for every cut.
	#INFO: This only applies when the tree is cut when using the mod.
	#Range: > 0
	damage_multiplicand = 1
	#When set to true, when a tree is broken and the tool is about to break we will just break enough blocks so that the tool is left at 1 of durability.
	preserve = false

