
#General settings
[general]
	#Extend time bonus, in ticks
	#Range: > 0
	extend_time = 10
	#Limits the number of times a given augment may be applied to a given effect
	#Example entry: "amplify=5"
	augment_limits = []
	#Cost
	#Range: > -2147483648
	cost = 0
	#The maximum number of times this glyph may appear in a single spell
	#Range: > 1
	per_spell_limit = 2147483647
	#Is Starter Glyph?
	starter = false
	#Base time in ticks
	#Range: > 0
	base_duration = 5
	#Is Enabled?
	enabled = true

